--
-- MySQL 5.0.77
-- Mon, 25 Apr 2011 01:17:35 +0000
--

CREATE DATABASE `rims` DEFAULT CHARSET latin1;

USE `rims`;

CREATE TABLE `admin_log` (
   `id` bigint(19) not null auto_increment,
   `ip` varchar(256) not null,
   `time` varchar(256) not null,
   `action` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=4;

INSERT INTO `admin_log` (`id`, `ip`, `time`, `action`) VALUES 
('1', '173.26.94.38', 'Sat, 23 Apr 11 22:56:39 -0500', 'Logged In'),
('2', '173.26.94.38', 'Sat, 23 Apr 11 22:57:09 -0500', 'Logged In'),
('3', '173.26.94.38', 'Sat, 23 Apr 11 23:18:54 -0500', 'Logged In');

CREATE TABLE `admin_msg` (
   `id` int(4) not null auto_increment,
   `username` varchar(256) not null,
   `message` text not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `admin_msg` is empty]

CREATE TABLE `bad_words` (
   `id` int(4) not null,
   `word` varchar(256) not null,
   `replacement` varchar(256) not null
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `bad_words` (`id`, `word`, `replacement`) VALUES 
('0', 'ahole ', '[censored]'),
('1', 'anus ', '[censored]'),
('2', 'ash0le ', '[censored]'),
('3', 'ash0les ', '[censored]'),
('4', 'asholes ', '[censored]'),
('5', 'ass ', '[censored]'),
('6', 'Ass Monkey ', '[censored]'),
('7', 'Assface ', '[censored]'),
('8', 'assh0le ', '[censored]'),
('9', 'assh0lez ', '[censored]'),
('10', 'asshole ', '[censored]'),
('11', 'assholes ', '[censored]'),
('12', 'assholz ', '[censored]'),
('13', 'asswipe ', '[censored]'),
('14', 'azzhole ', '[censored]'),
('15', 'bassterds ', '[censored]'),
('16', 'bastard ', '[censored]'),
('17', 'bastards ', '[censored]'),
('18', 'bastardz ', '[censored]'),
('19', 'basterds ', '[censored]'),
('20', 'basterdz ', '[censored]'),
('21', 'Biatch ', '[censored]'),
('22', 'bitch ', '[censored]'),
('23', 'bitches ', '[censored]'),
('24', 'Blow Job ', '[censored]'),
('25', 'boffing ', '[censored]'),
('26', 'butthole ', '[censored]'),
('27', 'buttwipe ', '[censored]'),
('28', 'c0ck ', '[censored]'),
('29', 'c0cks ', '[censored]'),
('30', 'c0k ', '[censored]'),
('31', 'Carpet Muncher ', '[censored]'),
('32', 'cawk ', '[censored]'),
('33', 'cawks ', '[censored]'),
('34', 'Clit ', '[censored]'),
('35', 'cnts ', '[censored]'),
('36', 'cntz ', '[censored]'),
('37', 'cock ', '[censored]'),
('38', 'cockhead ', '[censored]'),
('39', 'cock-head ', '[censored]'),
('40', 'cocks ', '[censored]'),
('41', 'CockSucker ', '[censored]'),
('42', 'cock-sucker ', '[censored]'),
('43', 'crap ', '[censored]'),
('44', 'cum ', '[censored]'),
('45', 'cunt ', '[censored]'),
('46', 'cunts ', '[censored]'),
('47', 'cuntz ', '[censored]'),
('48', 'dick ', '[censored]'),
('49', 'dild0 ', '[censored]'),
('50', 'dild0s ', '[censored]'),
('51', 'dildo ', '[censored]'),
('52', 'dildos ', '[censored]'),
('53', 'dilld0 ', '[censored]'),
('54', 'dilld0s ', '[censored]'),
('55', 'dominatricks ', '[censored]'),
('56', 'dominatrics ', '[censored]'),
('57', 'dominatrix ', '[censored]'),
('58', 'dyke ', '[censored]'),
('59', 'enema ', '[censored]'),
('60', 'f u c k ', '[censored]'),
('61', 'f u c k e r ', '[censored]'),
('62', 'fag ', '[censored]'),
('63', 'fag1t ', '[censored]'),
('64', 'faget ', '[censored]'),
('65', 'fagg1t ', '[censored]'),
('66', 'faggit ', '[censored]'),
('67', 'faggot ', '[censored]'),
('68', 'fagit ', '[censored]'),
('69', 'fags ', '[censored]'),
('70', 'fagz ', '[censored]'),
('71', 'faig ', '[censored]'),
('72', 'faigs ', '[censored]'),
('73', 'fart ', '[censored]'),
('74', 'flipping the bird ', '[censored]'),
('75', 'fuck ', '[censored]'),
('76', 'fucker ', '[censored]'),
('77', 'fuckin ', '[censored]'),
('78', 'fucking ', '[censored]'),
('79', 'fucks ', '[censored]'),
('80', 'Fudge Packer ', '[censored]'),
('81', 'fuk ', '[censored]'),
('82', 'Fukah ', '[censored]'),
('83', 'Fuken ', '[censored]'),
('84', 'fuker ', '[censored]'),
('85', 'Fukin ', '[censored]'),
('86', 'Fukk ', '[censored]'),
('87', 'Fukkah ', '[censored]'),
('88', 'Fukken ', '[censored]'),
('89', 'Fukker ', '[censored]'),
('90', 'Fukkin ', '[censored]'),
('91', 'g00k ', '[censored]'),
('92', 'gay ', '[censored]'),
('93', 'gayboy ', '[censored]'),
('94', 'gaygirl ', '[censored]'),
('95', 'gays ', '[censored]'),
('96', 'gayz ', '[censored]'),
('97', 'God-damned ', '[censored]'),
('98', 'h00r ', '[censored]'),
('99', 'h0ar ', '[censored]'),
('100', 'h0re ', '[censored]'),
('101', 'hells ', '[censored]'),
('102', 'hoar ', '[censored]'),
('103', 'hoor ', '[censored]'),
('104', 'hoore ', '[censored]'),
('105', 'jackoff ', '[censored]'),
('106', 'jap ', '[censored]'),
('107', 'japs ', '[censored]'),
('108', 'jerk-off ', '[censored]'),
('109', 'jisim ', '[censored]'),
('110', 'jiss ', '[censored]'),
('111', 'jizm ', '[censored]'),
('112', 'jizz ', '[censored]'),
('113', 'knob ', '[censored]'),
('114', 'knobs ', '[censored]'),
('115', 'knobz ', '[censored]'),
('116', 'kunt ', '[censored]'),
('117', 'kunts ', '[censored]'),
('118', 'kuntz ', '[censored]'),
('119', 'Lesbian ', '[censored]'),
('120', 'Lezzian ', '[censored]'),
('121', 'Lipshits ', '[censored]'),
('122', 'Lipshitz ', '[censored]'),
('123', 'masochist ', '[censored]'),
('124', 'masokist ', '[censored]'),
('125', 'massterbait ', '[censored]'),
('126', 'masstrbait ', '[censored]'),
('127', 'masstrbate ', '[censored]'),
('128', 'masterbaiter ', '[censored]'),
('129', 'masterbate ', '[censored]'),
('130', 'masterbates ', '[censored]'),
('131', 'Motha Fucker ', '[censored]'),
('132', 'Motha Fuker ', '[censored]'),
('133', 'Motha Fukkah ', '[censored]'),
('134', 'Motha Fukker ', '[censored]'),
('135', 'Mother Fucker ', '[censored]'),
('136', 'Mother Fukah ', '[censored]'),
('137', 'Mother Fuker ', '[censored]'),
('138', 'Mother Fukkah ', '[censored]'),
('139', 'Mother Fukker ', '[censored]'),
('140', 'mother-fucker ', '[censored]'),
('141', 'Mutha Fucker ', '[censored]'),
('142', 'Mutha Fukah ', '[censored]'),
('143', 'Mutha Fuker ', '[censored]'),
('144', 'Mutha Fukkah ', '[censored]'),
('145', 'Mutha Fukker ', '[censored]'),
('146', 'n1gr ', '[censored]'),
('147', 'nastt ', '[censored]'),
('148', 'nigger; ', '[censored]'),
('149', 'nigur; ', '[censored]'),
('150', 'niiger; ', '[censored]'),
('151', 'niigr; ', '[censored]'),
('152', 'orafis ', '[censored]'),
('153', 'orgasim; ', '[censored]'),
('154', 'orgasm ', '[censored]'),
('155', 'orgasum ', '[censored]'),
('156', 'oriface ', '[censored]'),
('157', 'orifice ', '[censored]'),
('158', 'orifiss ', '[censored]'),
('159', 'packi ', '[censored]'),
('160', 'packie ', '[censored]'),
('161', 'packy ', '[censored]'),
('162', 'paki ', '[censored]'),
('163', 'pakie ', '[censored]'),
('164', 'paky ', '[censored]'),
('165', 'pecker ', '[censored]'),
('166', 'peeenus ', '[censored]'),
('167', 'peeenusss ', '[censored]'),
('168', 'peenus ', '[censored]'),
('169', 'peinus ', '[censored]'),
('170', 'pen1s ', '[censored]'),
('171', 'penas ', '[censored]'),
('172', 'penis ', '[censored]'),
('173', 'penis-breath ', '[censored]'),
('174', 'penus ', '[censored]'),
('175', 'penuus ', '[censored]'),
('176', 'Phuc ', '[censored]'),
('177', 'Phuck ', '[censored]'),
('178', 'Phuk ', '[censored]'),
('179', 'Phuker ', '[censored]'),
('180', 'Phukker ', '[censored]'),
('181', 'polac ', '[censored]'),
('182', 'polack ', '[censored]'),
('183', 'polak ', '[censored]'),
('184', 'Poonani ', '[censored]'),
('185', 'pr1c ', '[censored]'),
('186', 'pr1ck ', '[censored]'),
('187', 'pr1k ', '[censored]'),
('188', 'pusse ', '[censored]'),
('189', 'pussee ', '[censored]'),
('190', 'pussy ', '[censored]'),
('191', 'puuke ', '[censored]'),
('192', 'puuker ', '[censored]'),
('193', 'queer ', '[censored]'),
('194', 'queers ', '[censored]'),
('195', 'queerz ', '[censored]'),
('196', 'qweers ', '[censored]'),
('197', 'qweerz ', '[censored]'),
('198', 'qweir ', '[censored]'),
('199', 'recktum ', '[censored]'),
('200', 'rectum ', '[censored]'),
('201', 'retard ', '[censored]'),
('202', 'sadist ', '[censored]'),
('203', 'scank ', '[censored]'),
('204', 'schlong ', '[censored]'),
('205', 'screwing ', '[censored]'),
('206', 'semen ', '[censored]'),
('207', 'sex ', '[censored]'),
('208', 'sexy ', '[censored]'),
('209', 'Sh!t ', '[censored]'),
('210', 'sh1t ', '[censored]'),
('211', 'sh1ter ', '[censored]'),
('212', 'sh1ts ', '[censored]'),
('213', 'sh1tter ', '[censored]'),
('214', 'sh1tz ', '[censored]'),
('215', 'shit ', '[censored]'),
('216', 'shits ', '[censored]'),
('217', 'shitter ', '[censored]'),
('218', 'Shitty ', '[censored]'),
('219', 'Shity ', '[censored]'),
('220', 'shitz ', '[censored]'),
('221', 'Shyt ', '[censored]'),
('222', 'Shyte ', '[censored]'),
('223', 'Shytty ', '[censored]'),
('224', 'Shyty ', '[censored]'),
('225', 'skanck ', '[censored]'),
('226', 'skank ', '[censored]'),
('227', 'skankee ', '[censored]'),
('228', 'skankey ', '[censored]'),
('229', 'skanks ', '[censored]'),
('230', 'Skanky ', '[censored]'),
('231', 'slut ', '[censored]'),
('232', 'sluts ', '[censored]'),
('233', 'Slutty ', '[censored]'),
('234', 'slutz ', '[censored]'),
('235', 'son-of-a-bitch ', '[censored]'),
('236', 'tit ', '[censored]'),
('237', 'turd ', '[censored]'),
('238', 'va1jina ', '[censored]'),
('239', 'vag1na ', '[censored]'),
('240', 'vagiina ', '[censored]'),
('241', 'vagina ', '[censored]'),
('242', 'vaj1na ', '[censored]'),
('243', 'vajina ', '[censored]'),
('244', 'vullva ', '[censored]'),
('245', 'vulva ', '[censored]'),
('246', 'w0p ', '[censored]'),
('247', 'wh00r ', '[censored]'),
('248', 'wh0re ', '[censored]'),
('249', 'whore ', '[censored]'),
('250', 'xrated ', '[censored]'),
('251', 'xxx', '[censored]'),
('252', 'b!+ch', '[censored]'),
('253', 'bitch', '[censored]'),
('254', 'blowjob', '[censored]'),
('255', 'clit', '[censored]'),
('256', 'arschloch', '[censored]'),
('257', 'fuck', '[censored]'),
('258', 'shit', '[censored]'),
('259', 'ass', '[censored]'),
('260', 'asshole', '[censored]'),
('261', 'b!tch', '[censored]'),
('262', 'b17ch', '[censored]'),
('263', 'b1tch', '[censored]'),
('264', 'bastard', '[censored]'),
('265', 'bi+ch', '[censored]'),
('266', 'boiolas', '[censored]'),
('267', 'buceta', '[censored]'),
('268', 'c0ck', '[censored]'),
('269', 'cawk', '[censored]'),
('270', 'chink', '[censored]'),
('271', 'cipa', '[censored]'),
('272', 'clits', '[censored]'),
('273', 'cock', '[censored]'),
('274', 'cum', '[censored]'),
('275', 'cunt', '[censored]'),
('276', 'dildo', '[censored]'),
('277', 'dirsa', '[censored]'),
('278', 'ejakulate', '[censored]'),
('279', 'fatass', '[censored]'),
('280', 'fcuk', '[censored]'),
('281', 'fuk', '[censored]'),
('282', 'fux0r', '[censored]'),
('283', 'hoer', '[censored]'),
('284', 'hore', '[censored]'),
('285', 'jism', '[censored]'),
('286', 'kawk', '[censored]'),
('287', 'l3itch', '[censored]'),
('288', 'l3i+ch', '[censored]'),
('289', 'lesbian', '[censored]'),
('290', 'masturbate', '[censored]'),
('291', 'masterbat*', '[censored]'),
('292', 'masterbat3', '[censored]'),
('293', 'motherfucker', '[censored]'),
('294', 's.o.b.', '[censored]'),
('295', 'mofo', '[censored]'),
('296', 'nazi', '[censored]'),
('297', 'nigga', '[censored]'),
('298', 'nigger', '[censored]'),
('299', 'nutsack', '[censored]'),
('300', 'phuck', '[censored]'),
('301', 'pimpis', '[censored]'),
('302', 'pusse', '[censored]'),
('303', 'pussy', '[censored]'),
('304', 'scrotum', '[censored]'),
('305', 'sh!t', '[censored]'),
('306', 'shemale', '[censored]'),
('307', 'shi+', '[censored]'),
('308', 'sh!+', '[censored]'),
('309', 'slut', '[censored]'),
('310', 'smut', '[censored]'),
('311', 'teets', '[censored]'),
('312', 'tits', '[censored]'),
('313', 'boobs', '[censored]'),
('314', 'b00bs', '[censored]'),
('315', 'teez', '[censored]'),
('316', 'testical', '[censored]'),
('317', 'testicle', '[censored]'),
('318', 'titt', '[censored]'),
('319', 'w00se', '[censored]'),
('320', 'jackoff', '[censored]'),
('321', 'wank', '[censored]'),
('322', 'whoar', '[censored]'),
('323', 'whore', '[censored]'),
('324', '*damn', '[censored]'),
('325', '*dyke', '[censored]'),
('326', '*fuck*', '[censored]'),
('327', '*shit*', '[censored]'),
('328', '@$$', '[censored]'),
('329', 'amcik', '[censored]'),
('330', 'andskota', '[censored]'),
('331', 'arse*', '[censored]'),
('332', 'assrammer', '[censored]'),
('333', 'ayir', '[censored]'),
('334', 'bi7ch', '[censored]'),
('335', 'bitch*', '[censored]'),
('336', 'bollock*', '[censored]'),
('337', 'breasts', '[censored]'),
('338', 'butt-pirate', '[censored]'),
('339', 'cabron', '[censored]'),
('340', 'cazzo', '[censored]'),
('341', 'chraa', '[censored]'),
('342', 'chuj', '[censored]'),
('343', 'Cock*', '[censored]'),
('344', 'cunt*', '[censored]'),
('345', 'd4mn', '[censored]'),
('346', 'daygo', '[censored]'),
('347', 'dego', '[censored]'),
('348', 'dick*', '[censored]'),
('349', 'dike*', '[censored]'),
('350', 'dupa', '[censored]'),
('351', 'dziwka', '[censored]'),
('352', 'ejackulate', '[censored]'),
('353', 'Ekrem*', '[censored]'),
('354', 'Ekto', '[censored]'),
('355', 'enculer', '[censored]'),
('356', 'faen', '[censored]'),
('357', 'fag*', '[censored]'),
('358', 'fanculo', '[censored]'),
('359', 'fanny', '[censored]'),
('360', 'feces', '[censored]'),
('361', 'feg', '[censored]'),
('362', 'Felcher', '[censored]'),
('363', 'ficken', '[censored]'),
('364', 'fitt*', '[censored]'),
('365', 'Flikker', '[censored]'),
('366', 'foreskin', '[censored]'),
('367', 'Fotze', '[censored]'),
('368', 'Fu(*', '[censored]'),
('369', 'fuk*', '[censored]'),
('370', 'futkretzn', '[censored]'),
('371', 'gay', '[censored]'),
('372', 'gook', '[censored]'),
('373', 'guiena', '[censored]'),
('374', 'h0r', '[censored]'),
('375', 'h4x0r', '[censored]'),
('376', 'hell', '[censored]'),
('377', 'helvete', '[censored]'),
('378', 'hoer*', '[censored]'),
('379', 'honkey', '[censored]'),
('380', 'Huevon', '[censored]'),
('381', 'hui', '[censored]'),
('382', 'injun', '[censored]'),
('383', 'jizz', '[censored]'),
('384', 'kanker*', '[censored]'),
('385', 'kike', '[censored]'),
('386', 'klootzak', '[censored]'),
('387', 'kraut', '[censored]'),
('388', 'knulle', '[censored]'),
('389', 'kuk', '[censored]'),
('390', 'kuksuger', '[censored]'),
('391', 'Kurac', '[censored]'),
('392', 'kurwa', '[censored]'),
('393', 'kusi*', '[censored]'),
('394', 'kyrpa*', '[censored]'),
('395', 'lesbo', '[censored]'),
('396', 'mamhoon', '[censored]'),
('397', 'masturbat*', '[censored]'),
('398', 'merd*', '[censored]'),
('399', 'mibun', '[censored]'),
('400', 'monkleigh', '[censored]'),
('401', 'mouliewop', '[censored]'),
('402', 'muie', '[censored]'),
('403', 'mulkku', '[censored]'),
('404', 'muschi', '[censored]'),
('405', 'nazis', '[censored]'),
('406', 'nepesaurio', '[censored]'),
('407', 'nigger*', '[censored]'),
('408', 'orospu', '[censored]'),
('409', 'paska*', '[censored]'),
('410', 'perse', '[censored]'),
('411', 'picka', '[censored]'),
('412', 'pierdol*', '[censored]'),
('413', 'pillu*', '[censored]'),
('414', 'pimmel', '[censored]'),
('415', 'piss*', '[censored]'),
('416', 'pizda', '[censored]'),
('417', 'poontsee', '[censored]'),
('418', 'poop', '[censored]'),
('419', 'porn', '[censored]'),
('420', 'p0rn', '[censored]'),
('421', 'pr0n', '[censored]'),
('422', 'preteen', '[censored]'),
('423', 'pula', '[censored]'),
('424', 'pule', '[censored]'),
('425', 'puta', '[censored]'),
('426', 'puto', '[censored]'),
('427', 'qahbeh', '[censored]'),
('428', 'queef*', '[censored]'),
('429', 'rautenberg', '[censored]'),
('430', 'schaffer', '[censored]'),
('431', 'scheiss*', '[censored]'),
('432', 'schlampe', '[censored]'),
('433', 'schmuck', '[censored]'),
('434', 'screw', '[censored]'),
('435', 'sh!t*', '[censored]'),
('436', 'sharmuta', '[censored]'),
('437', 'sharmute', '[censored]'),
('438', 'shipal', '[censored]'),
('439', 'shiz', '[censored]'),
('440', 'skribz', '[censored]'),
('441', 'skurwysyn', '[censored]'),
('442', 'sphencter', '[censored]'),
('443', 'spic', '[censored]'),
('444', 'spierdalaj', '[censored]'),
('445', 'splooge', '[censored]'),
('446', 'suka', '[censored]'),
('447', 'b00b*', '[censored]'),
('448', 'testicle*', '[censored]'),
('449', 'titt*', '[censored]'),
('450', 'twat', '[censored]'),
('451', 'vittu', '[censored]'),
('452', 'wank*', '[censored]'),
('453', 'wetback*', '[censored]'),
('454', 'wichser', '[censored]'),
('455', 'wop*', '[censored]'),
('456', 'yed', '[censored]'),
('457', 'zabourah', '[censored]'),
('458', 'suck', '[censored]');

CREATE TABLE `drive_team` (
   `id` int(4) not null auto_increment,
   `team_id` int(5) not null,
   `match_id` int(5) not null,
   `feedback` int(11) not null,
   `comment` varchar(256) not null,
   `user` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `drive_team` is empty]

CREATE TABLE `game_specific` (
   `id` int(4) not null auto_increment,
   `team_id` int(5) not null,
   `minibot_score` varchar(256) not null,
   `minibot` int(1) not null,
   `user` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=19;

INSERT INTO `game_specific` (`id`, `team_id`, `minibot_score`, `minibot`, `user`) VALUES 
('1', '1224', '', '0', 'joseph'),
('2', '3123', '', '0', 'joseph'),
('3', '231', '', '0', 'joseph'),
('4', '1953', '', '0', 'joseph'),
('5', '2673', '', '0', 'joseph'),
('6', '931', '', '0', 'rocky'),
('7', '6669', '', '0', 'rocky'),
('8', '8675', '', '0', 'rocky'),
('9', '1010', '', '0', 'rocky'),
('10', '8675', '', '0', 'rocky'),
('11', '324', '', '0', 'joseph'),
('12', '8675', '', '0', 'rocky'),
('13', '8675', '', '0', 'rocky'),
('14', '312', '', '0', 'rocky'),
('15', '8675', '', '0', 'admin'),
('16', '8675', '', '0', 'joseph'),
('17', '8675', '', '0', 'joseph'),
('18', '8675', '', '0', 'rocky');

CREATE TABLE `game_specific_fields` (
   `id` int(4) not null auto_increment,
   `field_type` int(1) not null,
   `field_id` varchar(256) not null,
   `field_label` varchar(256) not null,
   `list_value` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=2;

INSERT INTO `game_specific_fields` (`id`, `field_type`, `field_id`, `field_label`, `list_value`) VALUES 
('1', '2', 'minibot', 'minibot', '1 Yes 0 No');

CREATE TABLE `ip_log` (
   `id` bigint(19) not null auto_increment,
   `ip` varchar(256) not null,
   `time` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=2;

INSERT INTO `ip_log` (`id`, `ip`, `time`) VALUES 
('1', '150.199.20.130', 'Sat, 23 Apr 11 12:15:07 -0500');

CREATE TABLE `match_info` (
   `id` int(5) not null auto_increment,
   `team_id` int(5) not null,
   `alliance` int(1) not null,
   `match_id` int(5) not null,
   `score` int(5) not null,
   `win` int(1) not null,
   `performance` text not null,
   `auto` int(1) not null,
   `auto_score` int(5) not null,
   `tele` int(1) not null,
   `tele_score` int(5) not null,
   `penalty` int(4) not null,
   `comment` text not null,
   `user` varchar(256) not null,
   `minibot_score` tinyint(2) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `match_info` is empty]

CREATE TABLE `match_simp` (
   `id` int(4) not null auto_increment,
   `minibotScore` int(5) not null,
   `team_id` int(4) not null,
   `minibotStatus` tinyint(1) not null,
   `user` varchar(256) not null,
   `teleScore` int(5) not null,
   PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `match_simp` is empty]

CREATE TABLE `photo` (
   `id` int(4) not null auto_increment,
   `path` varchar(256) not null,
   `title` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=11;

INSERT INTO `photo` (`id`, `path`, `title`) VALUES 
('1', '../../match_photo/1-Picture 014.jpg', 'Debugging'),
('5', '../../match_photo/5-Picture 014.jpg', 'Programmers At work'),
('6', '../../match_photo/6-Picture 021.jpg', 'Debugging'),
('7', '../../match_photo/7-Picture 076.jpg', 'Testing Robot'),
('8', '../../match_photo/8-Picture 087.jpg', 'Testing'),
('9', '../../match_photo/9-Picture 096.jpg', 'Working..'),
('10', '../../match_photo/10-Photo.jpg', 'Auto');

CREATE TABLE `public_log` (
   `id` bigint(19) not null auto_increment,
   `ip` varchar(256) not null,
   `time` varchar(256) not null,
   `action` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `public_log` is empty]

CREATE TABLE `robot` (
   `id` int(5) not null auto_increment,
   `team_id` int(5) not null,
   `weight` double not null,
   `wheel` varchar(256) not null,
   `picture` varchar(256) not null,
   `other_detail` text not null,
   `user` varchar(256) not null,
   `pickup` varchar(256),
   `minibot` tinyint(1) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `robot` is empty]

CREATE TABLE `score_grid` (
   `id` int(4) not null auto_increment,
   `team_id` int(5) not null,
   `match_id` int(5) not null,
   `score_x` varchar(256) not null,
   `score_y` varchar(256) not null,
   `comment` text not null,
   `user` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `score_grid` is empty]

CREATE TABLE `system` (
   `id` int(4) not null auto_increment,
   `game_name` varchar(256) not null,
   `game_logo` varchar(256) not null,
   `game_year` int(4) not null,
   `game_type` varchar(256) not null,
   `game_location` varchar(256) not null,
   `game_comment` varchar(256) not null,
   `filter` int(1) not null,
   `safe_mode` int(1) not null,
   `safe_mode_comment` varchar(256) not null,
   `upload_mode` int(1) not null,
   `notice` text not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=2;

INSERT INTO `system` (`id`, `game_name`, `game_logo`, `game_year`, `game_type`, `game_location`, `game_comment`, `filter`, `safe_mode`, `safe_mode_comment`, `upload_mode`, `notice`) VALUES 
('1', 'Logo Motion', '../game_lnfo/FRC_LOGO_MOTION.jpg', '2011', 'National', 'St. Louis', 'Nothing', '1', '0', 'Testing RIMS connector.', '0', 'RIMS Connector test finished! Working on rims file structure.');

CREATE TABLE `teams` (
   `id` int(4) not null auto_increment,
   `team_id` int(5) not null,
   `name` varchar(256) not null,
   `picture` varchar(256) not null default 'NULL',
   `url` varchar(256) not null,
   `about` varchar(256) not null,
   `language` varchar(256) not null,
   `control` varchar(256) not null,
   `parts_broken` text not null,
   `comment` text not null,
   `driver_picture` varchar(256) not null default 'NULL',
   `logo` varchar(256) not null default 'NULL',
   `division` varchar(1) not null,
   `user` varchar(256) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- [Table `teams` is empty]

CREATE TABLE `user` (
   `id` int(11) not null auto_increment,
   `username` varchar(256) not null,
   `password` varchar(32) not null,
   `type` smallint(1) not null,
   `ban` smallint(1) not null,
   `disable_edit` smallint(1) not null,
   `disable` int(1) not null,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
